n = int(input())
print('The next number for the number ', str(n), sep='', end='')
print(' is ', str(n + 1), '.', sep='')
print('The previous number for the number ', str(n), sep='', end='')
print(' is ', str(n - 1), '.', sep='')
